# Perform LU decomposition for square matrix

In [1]:
import numpy as np
import scipy.linalg as lg
import csv

In [2]:
matrix=open("matrix.csv")
A=np.loadtxt(matrix, dtype='int', delimiter=',')
A

array([[40, 35, 20],
       [65, 25, 15],
       [75, 83, 90]])

In [3]:
P, L, U=lg.lu(A)

In [4]:
print(" \n Lower Traingle:\n")
L

 
 Lower Traingle:



array([[1.        , 0.        , 0.        ],
       [0.86666667, 1.        , 0.        ],
       [0.53333333, 0.19744318, 1.        ]])

In [5]:
print(" \n Upper Traingle:\n")
U

 
 Upper Traingle:



array([[ 75.        ,  83.        ,  90.        ],
       [  0.        , -46.93333333, -63.        ],
       [  0.        ,   0.        , -15.56107955]])

In [6]:
decomposition=P.dot((L.dot(U)))

In [7]:
print("\n After LU decomposition, Original matrix is given below: \n")
decomposition


 After LU decomposition, Original matrix is given below: 



array([[40., 35., 20.],
       [65., 25., 15.],
       [75., 83., 90.]])