# Solve the equation Ax=b and check whether there are 0,1 or infinitely many solutions

In [1]:
import numpy as np
import csv

In [2]:
matrix=open("matrix.csv")
A1=np.loadtxt(matrix, dtype='int', delimiter=',')
A1

array([[40, 35, 20],
       [65, 25, 15],
       [75, 83, 90]])

In [3]:
vector=open("vector b.csv")
B1=np.loadtxt(vector, dtype='int', delimiter=',')
B1

array([ 9, 15, 25])

In [4]:
result=np.linalg.solve(A1,B1)
print("result : ")
result

result : 


array([ 0.23149247, -0.11821086,  0.19388407])