# Give exponential, sine and sigmoid functions on A

In [1]:
import numpy as np  
import csv

In [2]:
matrix=open("matrix.csv")
A=np.loadtxt(matrix, dtype='int', delimiter=',')
A

array([[40, 35, 20],
       [65, 25, 15],
       [75, 83, 90]])

# Exponential Function

In [3]:
print("\n Exponential Value:")
print(np.exp(A))


 Exponential Value:
[[2.35385267e+17 1.58601345e+15 4.85165195e+08]
 [1.69488924e+28 7.20048993e+10 3.26901737e+06]
 [3.73324200e+32 1.11286375e+36 1.22040329e+39]]


# Sine Function

In [4]:
print("\n Sine Value:")
print(np.sin(A * np.pi / 180))


 Sine Value:
[[0.64278761 0.57357644 0.34202014]
 [0.90630779 0.42261826 0.25881905]
 [0.96592583 0.99254615 1.        ]]


# Sigmoid Function

In [5]:
print("\n Sigmoid Value:")
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

print(sigmoid(A))


 Sigmoid Value:
[[1.         1.         1.        ]
 [1.         1.         0.99999969]
 [1.         1.         1.        ]]
