# Give exponential, sine and sigmoid functions on A

In [1]:
import numpy as np  
import csv
from sympy import *

In [2]:
matrix=open("matrix.csv")
A=np.loadtxt(matrix, dtype='int', delimiter=',')
A1=Matrix(A)
A1

Matrix([
[11,  3, 5],
[ 6,  8, 9],
[ 2, 23, 4]])

# Exponential Function

In [3]:
print("\n Exponential Value:")
print(np.exp(A))


 Exponential Value:
[[5.98741417e+04 2.00855369e+01 1.48413159e+02]
 [4.03428793e+02 2.98095799e+03 8.10308393e+03]
 [7.38905610e+00 9.74480345e+09 5.45981500e+01]]


### Proper Matrix Format Output

In [4]:
EXP1=Matrix(np.exp(A))
EXP1

Matrix([
[59874.1417151978, 20.0855369231877, 148.413159102577],
[403.428793492735, 2980.95798704173, 8103.08392757538],
[7.38905609893065,  9744803446.2489, 54.5981500331442]])

# Sine Function

In [5]:
print("\n Sine Value:")
print(np.sin(A * np.pi / 180))


 Sine Value:
[[0.190809   0.05233596 0.08715574]
 [0.10452846 0.1391731  0.15643447]
 [0.0348995  0.39073113 0.06975647]]


### Proper Matrix Format Output

In [6]:
SINE=Matrix(np.sin(A * np.pi / 180))
SINE

Matrix([
[0.190808995376545, 0.0523359562429438, 0.0871557427476582],
[0.104528463267653,  0.139173100960065,  0.156434465040231],
[0.034899496702501,  0.390731128489274, 0.0697564737441253]])

# Sigmoid Function

In [7]:
print("\n Sigmoid Value:")
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

print(sigmoid(A))


 Sigmoid Value:
[[0.9999833  0.95257413 0.99330715]
 [0.99752738 0.99966465 0.99987661]
 [0.88079708 1.         0.98201379]]


### Proper Matrix Format Output

In [8]:
SIG=Matrix(sigmoid(A))
SIG

Matrix([
[0.999983298578152, 0.952574126822433, 0.993307149075715],
[0.997527376843365, 0.999664649869534, 0.999876605424014],
[0.880797077977882, 0.999999999897381, 0.982013790037908]])