# Find all the eigenpairs of A

In [1]:
import numpy as np
from numpy.linalg import eig

In [2]:
matrix=open("matrix.csv")
A=np.loadtxt(matrix, dtype='int', delimiter=',')
A

array([[40, 35, 20],
       [65, 25, 15],
       [75, 83, 90]])

# EIGEN VALUES

In [3]:
EigenValues,EigenVector=eig(A)

In [4]:
print("\n Eigen-value: \n", EigenValues)


 Eigen-value: 
 [138.99946117 -13.40231423  29.40285306]


# EIGEN VECTOR

In [5]:
print("\n E-vector \n", EigenVector)


 E-vector 
 [[ 0.28506783  0.40602799 -0.23059789]
 [ 0.28303553 -0.83356088 -0.42919669]
 [ 0.91576592  0.37458981  0.8732782 ]]
