# Find all the eigenpairs of A

In [1]:
import numpy as np
from numpy.linalg import eig
from sympy import *

In [2]:
matrix=open("matrix.csv")
A=np.loadtxt(matrix, dtype='int', delimiter=',')
A1=Matrix(A)
A1

Matrix([
[11,  3, 5],
[ 6,  8, 9],
[ 2, 23, 4]])

# EIGEN VALUES

In [3]:
EigenValues,EigenVector=eig(A)

In [4]:
print("\n Eigen-value: \n", EigenValues)


 Eigen-value: 
 [23.61635531  7.21105817 -7.82741348]


### Proper Matrix Format Output

In [5]:
EVal=Matrix(EigenValues)
EVal

Matrix([
[ 23.6163553109334],
[ 7.21105817316263],
[-7.82741348409609]])

# EIGEN VECTOR

In [6]:
print("\n E-vector \n", EigenVector)


 E-vector 
 [[-0.41636004 -0.82887517 -0.1644141 ]
 [-0.56876957  0.14741879 -0.43974485]
 [-0.7093275   0.53966068  0.88294534]]


### Proper Matrix Format Output

In [7]:
EVec=Matrix(EigenVector)
EVec

Matrix([
[-0.416360038534106, -0.828875168798118, -0.164414096150051],
[-0.568769569438257,  0.147418790871596,  -0.43974484541052],
[-0.709327495021092,  0.539660684734257,  0.882945341412502]])